// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace LibraryBackend.Models
{
    public partial class Book
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Author { get; set; }
        public string BookDescription { get; set; }
        [Url]
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
        [Required]
        public decimal Price { get; set; }
        public int? Quantity { get; set; }
        [Required]
        public bool IsRentable { get; set; }
        public string? Rating { get; set; }   
    }
}