// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace LibraryBackend.Models
{
    public partial class RentedBook
    {
        public int Id { get; set; }
        [Required]
        public int BookId { get; set; }
        [Required]
        public int UserId { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime RentalDate { get; set; }
        public DateTime? DateOfReturn { get; set; }

        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}