// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace LibraryBackend.Models
{
    public partial class Role
    {
        public int Id { get; set; }
        [Required]
        public string RoleName { get; set; }
    }
}